- name: Check apache if web server is running
  shell: 'ps -ef | grep [a]pache'
  register: apache_status
  changed_when: false
  when: ansible_local.patching.webserver == 'true'

- name: check database if database server is running
  shell: 'ps -ef | grep [m]ysql'
  register: mysql_status
  changed_when: false
  when: ansible_local.patching.database == 'true'