- hosts: all
  gather_facts: true
  vars:
  tasks:

  roles:
  - precheck
  - { role: fact_push, when: ansible_local.patching.rebooting == "true" }
  - patch
  - reboot
  - server_validation
  - app_validation
  - { role: report, when: report | default(false) == "true" }